<Project>
  <Target Name="ExtractLicensesOnBuild" AfterTargets="Build" Condition="'$(AssemblyName)' != 'LicenseExtractor'">
    <MSBuild Projects="$(MSBuildThisFileDirectory)LicenseExtractor\LicenseExtractor.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
    <Exec Command="dotnet &quot;$(MSBuildThisFileDirectory)LicenseExtractor\bin\$(Configuration)\net10.0\LicenseExtractor.dll&quot; &quot;$(MSBuildThisFileDirectory).&quot; &quot;$([System.IO.Path]::GetFullPath('$(TargetDir)Open-Source_Attribution'))&quot;" />
  </Target>

  <Target Name="ExtractLicensesOnPublish" AfterTargets="Publish" Condition="'$(AssemblyName)' != 'LicenseExtractor' And '$(PublishDir)' != ''">
    <MSBuild Projects="$(MSBuildThisFileDirectory)LicenseExtractor\LicenseExtractor.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
    <Exec Command="dotnet &quot;$(MSBuildThisFileDirectory)LicenseExtractor\bin\$(Configuration)\net10.0\LicenseExtractor.dll&quot; &quot;$(MSBuildThisFileDirectory).&quot; &quot;$([System.IO.Path]::GetFullPath('$(PublishDir)Open-Source_Attribution'))&quot;" />
  </Target>
</Project>
