using Arch.Core;
using Realm.Ecs.Components.Combat;
using Realm.Ecs.Components.Core;
using Realm.Ecs.Components.Movement;
using Realm.Ecs.Components.Resources;
using Realm.Ecs.Components.Tags;
using Realm.Ecs.Components.Terrain;
using Realm.Ecs.Components.Stats;
using Realm.Ecs.Services;

namespace Realm.Ecs.Common;

public static class QueryCache
{
    public static readonly QueryDescription AllStatModifierQuery = new QueryDescription().WithAll<StatModifier>();
    public static readonly QueryDescription AllPositionAndDefinitionIdQuery = new QueryDescription().WithAll<Position, DefinitionId>();
    public static readonly QueryDescription AllInterpolationTargetQuery = new QueryDescription().WithAll<InterpolationTarget>();
    public static readonly QueryDescription AllPositionAndMoveToAndMovementStatsNoneDeadQuery = new QueryDescription().WithAll<Position, MoveTo, MovementStats>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndDefinitionIdNoneDeadQuery = new QueryDescription().WithAll<Position, DefinitionId>().WithNone<Dead>();
    public static readonly QueryDescription AllTerrainStateAndEditorStateQuery = new QueryDescription().WithAll<TerrainState, EditorState>();
    public static readonly QueryDescription AllUnitSpawnRequestQuery = new QueryDescription().WithAll<UnitSpawnRequest>();
    public static readonly QueryDescription AllPropSpawnRequestQuery = new QueryDescription().WithAll<PropSpawnRequest>();
    public static readonly QueryDescription AllDecalSpawnRequestQuery = new QueryDescription().WithAll<DecalSpawnRequest>();
    public static readonly QueryDescription AllShroudStateQuery = new QueryDescription().WithAll<ShroudState>();
    public static readonly QueryDescription AllWeatherStateQuery = new QueryDescription().WithAll<WeatherState>();
    public static readonly QueryDescription AllHealthAndOwnerQuery = new QueryDescription().WithAll<Health, Owner>();
    public static readonly QueryDescription AllPositionAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Position, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndHealthAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Position, Health, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndAttackAndOwnerNoneAttackTargetAndDeadQuery = new QueryDescription().WithAll<Position, Attack, Owner>().WithNone<AttackTarget, Dead>();
    public static readonly QueryDescription AllPositionAndAttackAndAttackTargetAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Position, Attack, AttackTarget, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndOwnerAndDefinitionIdNoneDeadAndHealingTargetQuery = new QueryDescription().WithAll<Position, Owner, DefinitionId>().WithNone<Dead, HealingTarget>();
    public static readonly QueryDescription AllPositionAndAttackAndHealingTargetAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Position, Attack, HealingTarget, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllWorldStateQuery = new QueryDescription().WithAll<WorldState>();
    public static readonly QueryDescription AllCombatAlertStateQuery = new QueryDescription().WithAll<CombatAlertState>();
    public static readonly QueryDescription AllPositionAndHealthNoneDeadQuery = new QueryDescription().WithAll<Position, Health>().WithNone<Dead>();
    public static readonly QueryDescription AllNetworkMappingStateQuery = new QueryDescription().WithAll<NetworkMappingState>();
    public static readonly QueryDescription AllReplayStateAndNetworkMappingStateQuery = new QueryDescription().WithAll<ReplayState, NetworkMappingState>();
    public static readonly QueryDescription AllDefinitionIdAndPositionAndOwnerQuery = new QueryDescription().WithAll<DefinitionId, Position, Owner>();
    public static readonly QueryDescription AllTerrainStateQuery = new QueryDescription().WithAll<TerrainState>();
    public static readonly QueryDescription AllReplayStateQuery = new QueryDescription().WithAll<ReplayState>();
    public static readonly QueryDescription AllNetworkStateQuery = new QueryDescription().WithAll<NetworkState>();
    public static readonly QueryDescription AllAttackAndOwnerNoneDeadAndBuildingQuery = new QueryDescription().WithAll<Attack, Owner>().WithNone<Dead, Building>();
    public static readonly QueryDescription AllArmorAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Armor, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllInputStateQuery = new QueryDescription().WithAll<InputState>();
    public static readonly QueryDescription AllBuildingAndOwnerAndPositionNoneDeadQuery = new QueryDescription().WithAll<Building, Owner, Position>().WithNone<Dead>();
    public static readonly QueryDescription AllOwnerAndMovableNoneDeadAndBuildingQuery = new QueryDescription().WithAll<Owner, Movable>().WithNone<Dead, Building>();
    public static readonly QueryDescription AllOwnerAndBuildingNoneDeadQuery = new QueryDescription().WithAll<Owner, Building>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionNoneDeadQuery = new QueryDescription().WithAll<Position>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndOwnerAndInventoryNoneDeadAndBuildingQuery = new QueryDescription().WithAll<Position, Owner, Inventory>().WithNone<Dead, Building>();
    public static readonly QueryDescription AllPositionAndGathererNoneDeadQuery = new QueryDescription().WithAll<Position, Gatherer>().WithNone<Dead>();
    public static readonly QueryDescription AllPlayerResourcesNoneDeadQuery = new QueryDescription().WithAll<PlayerResources>().WithNone<Dead>();
    public static readonly QueryDescription AllPositionAndResourceNodeAndPropIdentityQuery = new QueryDescription().WithAll<Position, ResourceNode, PropIdentity>();
    public static readonly QueryDescription AllPositionAndDefinitionIdAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Position, DefinitionId, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllBuffsNoneDeadQuery = new QueryDescription().WithAll<Buffs>().WithNone<Dead>();
    public static readonly QueryDescription AllBuffStateNoneDeadQuery = new QueryDescription().WithAll<BuffState>().WithNone<Dead>();
    public static readonly QueryDescription AllPatrolAndPositionNoneDeadAndAttackTargetQuery = new QueryDescription().WithAll<Patrol, Position>().WithNone<Dead, AttackTarget>();
    public static readonly QueryDescription AllFollowAndPositionNoneDeadQuery = new QueryDescription().WithAll<Follow, Position>().WithNone<Dead>();
    public static readonly QueryDescription AllAttackQuery = new QueryDescription().WithAll<Attack>();
    public static readonly QueryDescription AllProductionQueueQuery = new QueryDescription().WithAll<ProductionQueue>();
    public static readonly QueryDescription AllSpellCooldownsQuery = new QueryDescription().WithAll<SpellCooldowns>();
    public static readonly QueryDescription AllCooldownsQuery = new QueryDescription().WithAll<Cooldowns>();
    public static readonly QueryDescription AllPositionQuery = new QueryDescription().WithAll<Position>();
    public static readonly QueryDescription AllPropIdentityAndPositionQuery = new QueryDescription().WithAll<PropIdentity, Position>();
    public static readonly QueryDescription AllDecalIdentityAndPositionQuery = new QueryDescription().WithAll<DecalIdentity, Position>();
    public static readonly QueryDescription AllPositionAndCollisionRadiusQuery = new QueryDescription().WithAll<Position, CollisionRadius>();
    public static readonly QueryDescription AllPositionAndBuildTaskNoneDeadQuery = new QueryDescription().WithAll<Position, BuildTask>().WithNone<Dead>();
    public static readonly QueryDescription AllBuildingAndConstructionStateAndOwnerNoneDeadQuery = new QueryDescription().WithAll<Building, ConstructionState, Owner>().WithNone<Dead>();
    public static readonly QueryDescription AllBuildQueueNoneDeadQuery = new QueryDescription().WithAll<BuildQueue>().WithNone<Dead>();
    public static readonly QueryDescription AllIdleMovableQuery = new QueryDescription().WithAll<Owner, Movable>().WithNone<Dead, Building, MoveTo, AttackTarget, AttackMove, Patrol, Follow, HealingTarget>();
    public static readonly QueryDescription AllPositionAndMoveToAndPathFollowNoneDeadQuery = new QueryDescription().WithAll<Position, MoveTo, PathFollow>().WithNone<Dead>();
}
