<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Realm.Lobby\Realm.Lobby.csproj" />
    <ProjectReference Include="..\Realm.Ecs\Realm.Ecs.csproj" />
    <ProjectReference Include="..\Realm.MapAPI\Realm.MapAPI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="SharpCompress" Version="0.49.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>
</Project>