<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <Version>0.1.0-alpha</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\ThirdPartyBinaries\**\*.*">
      <Link>ThirdPartyBinaries\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </EmbeddedResource>
    <None Include="..\ThirdPartyBinaries\**\*.*">
      <Link>ThirdPartyBinaries\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>
</Project>
