<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <Version>0.0.1-Pre-Alpha</Version>
    <InformationalVersion>0.0.1_Pre-Alpha</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\ThirdPartyBinaries\**\*.*">
      <Link>ThirdPartyBinaries\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </EmbeddedResource>
    <None Include="..\ThirdPartyBinaries\**\*.*">
      <Link>ThirdPartyBinaries\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="MiaSetup\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="NSec.Cryptography" Version="26.4.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
  </ItemGroup>
</Project>
